### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by nuwrss** [WebAhead7/Doit#10]
I like your design its so simple 
but you have to make a margin between the checkbox and the text in every cell .

**Comment by Karyum** [comment]
Yeah I agree I would add margin before the checkboxes, I would also maybe make the width of the todo list (and the form above) be 50% of the screen. cause for big screens the list would be really stretched out

**Comment by Lujain-AbdUllatif** [comment]
Issue is solved, thanks for the note.

https://github.com/WebAhead7/Doit/blob/50881b6a8b2840e8b5551637209d7879bebbd998/index.css#L68
