### ISSUE TITLE
CheckNote is not needed if you use classList.toggle

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/Doit#15]
Although I do not encourage to build the project this way but it's a bit late for this now.

if you just want to toggle the strikethrough in and off, just add the strikethrough in a class and instead of using the `checkNote` function you could just toggle the class when someone clicks the checkbox

**Comment by Lujain-AbdUllatif** [comment]
SOLVED 👍 
add and remove instead of toggle 

https://github.com/WebAhead7/Doit/blob/50881b6a8b2840e8b5551637209d7879bebbd998/index.js#L102
